# Frontend Dockerfile
FROM node:20 as frontend_build

RUN apt-get update && apt-get install -y \
    jq 

WORKDIR /app

ARG BACKEND_URL
ENV BACKEND_URL $BACKEND_URL
RUN echo "BACKEND_URL: $BACKEND_URL"


COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx
COPY --from=frontend_build /app/dist/ /usr/share/nginx/html
COPY /nginx.conf /etc/nginx/conf.d/default.conf
COPY start-nginx.sh /start-nginx.sh
RUN chmod +x /start-nginx.sh

COPY ./env.sh /env.sh
RUN chmod +x /env.sh

# ENV BACKEND_URL=$BACKEND_URL
CMD ["/bin/sh", "-c", "/env.sh && /start-nginx.sh"]
# CMD ["npm", "run", "dev", "--host"]